version: '3.7'
services:
  qashier:
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - './src:/app/src'
    container_name: carpark_availability
    expose:
      - '4001'
    ports:
      - '4001:4001'
    # command: pnpm preview
